name = "curl-do"
route = { pattern = "*/*", zone_name = "curl.do" }
main = "dist/index.mjs"
usage_model = "unbound"
compatibility_date = "2022-09-23"
logpush = true

services = [
  { binding = "CTX", service = "ctx-do", environment = "production" }
]

kv_namespaces = [
  { binding = "STORAGE", id = "cf01cf26328a4b1a80037507d5e9b47c" }
]

[build]
command = "npm run build"
 
[build.upload]
format = "modules"

[miniflare]
env_path = ".env"
durable_objects_persist = "./data/"
kv_persist = "./data/"

[miniflare.mounts]
ctx-do = "../ctx.do"